# fly.toml app configuration file generated for market-clone-3 on 2024-10-08T16:44:35+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'market-clone-3'
primary_region = 'nrt'
[build]
#  image = "flyio/hellofly:latest"
  builder = "heroku/builder:22"
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
